import{a as g,S as b,i as a}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function d(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=d(r);fetch(r.href,o)}})();const L="17309902-7cbadf7b99e6a7450a84508e7";async function h(e,t=1){const d="https://pixabay.com/api/",s={key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};try{return(await g.get(d,{params:s})).data}catch(r){throw console.error("Fetch error:",r),r}}const p=e=>`
    <li class="gallery-card">
      <a href="${e.largeImageURL}" target="_blank">
        <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-img" />
      </a>
      <div class="info">
        <p><b>Likes</b> ${e.likes}</p>
        <p><b>Views</b> ${e.views}</p>
        <p><b>Comments</b> ${e.comments}</p>
        <p><b>Downloads</b> ${e.downloads}</p>
      </div>
    </li>`,w=()=>new b(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250,scrollZoom:!1}),S=()=>{document.querySelector(".gallery").innerHTML=""},v=document.querySelector(".form"),f=document.querySelector(".gallery"),y=document.querySelector(".loader"),m=document.querySelector(".more-btn");let n=null,i="",l=1;function E(){y.classList.remove("is-hidden")}function c(){y.classList.add("is-hidden")}const q=async e=>{if(e.preventDefault(),E(),i=e.currentTarget.elements.search_text.value.trim(),!i){a.show({color:"red",message:"Please enter a search query!"}),c();return}e.currentTarget.elements.search_text.value="",l=1,S();try{const t=await h(i,l);if(!t.hits.length){a.show({color:"red",message:"No images found. Try a different search!"}),c();return}f.innerHTML=t.hits.map(p).join(""),m.classList.toggle("is-hidden",t.hits.length<15),n?n.refresh():n=w()}catch{a.show({color:"red",message:"Error loading images. Please try again later."})}finally{c()}},T=async()=>{try{l++;const e=await h(i,l);if(!e.hits.length){a.show({color:"yellow",message:"No more images to load!"}),m.classList.add("is-hidden");return}f.insertAdjacentHTML("beforeend",e.hits.map(p).join("")),n.refresh();const t=document.querySelector(".gallery-card");t&&window.scrollBy({top:t.getBoundingClientRect().height*4,behavior:"smooth"})}catch(e){console.error(e)}};v.addEventListener("submit",q);m.addEventListener("click",T);document.addEventListener("DOMContentLoaded",c);
//# sourceMappingURL=index.js.map
