import{a as v,S,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const h of o.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&l(h)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const E="17309902-7cbadf7b99e6a7450a84508e7";async function p(e,t=1){const a="https://pixabay.com/api/",l={key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};try{return(await v.get(a,{params:l})).data}catch(r){throw console.error("Fetch error:",r),r}}const q=e=>`
    <li class="gallery-card">
      <a href="${e.largeImageURL}" target="_blank">
        <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-img" />
      </a>
      <div class="info">
        <p><b>Likes</b> ${e.likes}</p>
        <p><b>Views</b> ${e.views}</p>
        <p><b>Comments</b> ${e.comments}</p>
        <p><b>Downloads</b> ${e.downloads}</p>
      </div>
    </li>`,y=(e,t)=>{t.insertAdjacentHTML("beforeend",e.map(q).join(""))},f=()=>{document.querySelector(".gallery").innerHTML=""},x=()=>new S(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250,scrollZoom:!1}),B=document.querySelector(".form"),g=document.querySelector(".gallery"),b=document.querySelector(".loader"),m=document.querySelector(".more-btn");let c=null,i="",d=1;function L(){b.classList.remove("is-hidden")}function s(){b.classList.add("is-hidden")}function w(){m.classList.remove("is-hidden")}function u(){m.classList.add("is-hidden")}const M=async e=>{if(e.preventDefault(),L(),u(),i=e.currentTarget.elements.search_text.value.trim(),e.currentTarget.elements.search_text.value="",d=1,!i){s(),n.show({color:"red",message:"Please enter a search query."});return}try{const t=await p(i,d);if(!t.hits.length){f(),n.show({color:"red",message:"Sorry, no images found. Try another search!"}),s();return}f(),y(t.hits,g),c?c.refresh():c=x(),s(),t.hits.length<15?u():w()}catch(t){n.show({color:"red",message:"Error loading images. Please try again later."}),console.error(t),s()}},O=async()=>{d++,L(),u();try{const e=await p(i,d);if(!e.hits.length){n.show({color:"red",message:"You have reached the end of the collection."}),s();return}y(e.hits,g),c&&c.refresh();const t=document.querySelectorAll(".gallery-card");if(t.length>0){const a=t[0].getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}s(),e.hits.length<15?(u(),n.show({color:"blue",message:"We're sorry, but you've reached the end of search results."})):w()}catch(e){console.error(e),s()}};B.addEventListener("submit",M);m.addEventListener("click",O);document.addEventListener("DOMContentLoaded",s);
//# sourceMappingURL=index.js.map
