import{a as y,S as b,i as h}from"./assets/vendor-Db2TdIkw.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const L="17309902-7cbadf7b99e6a7450a84508e7";function m(t,r=1){const s="https://pixabay.com/api/",n={key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return y.get(s,{params:n}).then(e=>e.data).catch(e=>{throw console.error("Fetch error:",e),e})}const p=t=>`
    <li class="gallery-card">
      <a href="${t.largeImageURL}" target="_blank">
        <img src="${t.webformatURL}" alt="${t.tags}" class="gallery-img" />
      </a>
      <div class="info">
        <p><b>Likes</b> ${t.likes}</p>
        <p><b>Views</b> ${t.views}</p>
        <p><b>Comments</b> ${t.comments}</p>
        <p><b>Downloads</b> ${t.downloads}</p>
      </div>
    </li>`,w=()=>new b(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250,scrollZoom:!1}),v=document.querySelector(".form"),g=document.querySelector(".gallery"),f=document.querySelector(".loader.is-hidden"),l=document.querySelector(".more-btn");let i=null,c="",d=1;function S(){f.classList.remove("is-hidden")}function a(){f.classList.add("is-hidden")}const E=async t=>{if(t.preventDefault(),S(),c=t.currentTarget.elements.search_text.value.trim(),t.currentTarget.elements.search_text.value="",d=1,!c){a();return}try{const r=await m(c,d);if(console.log(r.hits),!r.hits.length){h.show({color:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),a();return}g.innerHTML=r.hits.map(p).join(""),r.hits.length<15?l.classList.add("is-hidden"):l.classList.remove("is-hidden"),i?i.refresh():i=w(),a()}catch(r){h.show({color:"red",message:"Error loading images. Please try again later."}),console.error(r),a()}},q=async()=>{try{d++;const t=await m(c,d);g.insertAdjacentHTML("beforeend",t.hits.map(p).join("")),i&&i.refresh();const r=document.querySelectorAll(".gallery-card");if(r.length>0){const s=r[0].getBoundingClientRect().height;window.scrollBy({top:s*4,behavior:"smooth"})}t.hits.length<15&&l.classList.add("is-hidden")}catch(t){console.error(t)}};v.addEventListener("submit",E);l.addEventListener("click",q);document.addEventListener("DOMContentLoaded",a);
//# sourceMappingURL=index.js.map
